---
title: "Question4"
author: "Ramzan Kamoto"
date: "2024-11-27"
output: powerpoint_presentation
---

## Portfolio Commentary

- Snake Oil capital closely follows its benchmark 
- Outperforms benchmark since Oct 2023
- Resources and Industrials contribute most to upswings and downswings 



```{r setup, include=FALSE, echo=FALSE}


rm(list = ls()) # Clean your environment:
gc() # garbage collection - It can be useful to call gc after a large object has been removed, as this may prompt R to return memory to the operating system.
library(tidyverse);library(dplyr);library(PerformanceAnalytics);library(tbl2xts)
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))

```



```{r, echo = FALSE}


Port_Holds <- read_rds("/Users/ramzankamoto/Documents/Masters/Fin Metrics/23550716fmx/data/Fund_Holds.rds") 

Port_Rets <- read_rds("/Users/ramzankamoto/Documents/Masters/Fin Metrics/23550716fmx/data/Fund_Rets.rds") 

BM_Holds <- read_rds("/Users/ramzankamoto/Documents/Masters/Fin Metrics/23550716fmx/data/BM_Holds.rds")


BM_Rets <- read_rds("/Users/ramzankamoto/Documents/Masters/Fin Metrics/23550716fmx/data/BM_Rets.rds")



```


```{r, echo=FALSE}
# Compare BM and Fund Returns
cum_ret_df <- prepare_cumulative_returns_q4(Port_Rets, BM_Rets)

# Convert to xts
xts_data <- convert_to_xts_q4(cum_ret_df)
```

## Rolling Cummulative returns 


```{r}
# Generate Charts
generate_charts_q4(xts_data)
```

## Performance Metrics vs BM  


```{r, echo=FALSE}
# Generate Summary Statistics
sfm_summary <- generate_summary_q4(xts_data)

print(sfm_summary)
```





## Sector Contribution 



```{r, echo = FALSE}
# Fund Positioning: Add Sector Data
port_holds_sector <- add_sector_data_q4(Port_Holds, BM_Holds)

# Calculate Sector Contributions
sector_contributions <- calculate_sector_contributions_q4(port_holds_sector, Port_Rets)

# Plot Sector Contributions
plot_sector_contributions_q4(sector_contributions)



```


