---
title: "Question1"
author: "Ramzan Kamoto"
date: "2024-11-27"
output:
  pdf_document: default
  html_document: default
---

## Systematic AI Fund 


```{r setup, include=FALSE}

rm(list = ls()) # Clean your environment:
gc() # garbage collection - It can be useful to call gc after a large object has been removed, as this may prompt R to return memory to the operating system.
library(tidyverse)
library(dplyr)
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```

## Initialize

```{r}
# Load Data
ASISA <- read_rds("/Users/ramzankamoto/Documents/Masters/Fin Metrics/23550716fmx/data/ASISA_Rets.rds")
BM <- read_rds("/Users/ramzankamoto/Documents/Masters/Fin Metrics/23550716fmx/data/Capped_SWIX.rds")
AI_Fund <- read_rds("/Users/ramzankamoto/Documents/Masters/Fin Metrics/23550716fmx/data/AI_Max_Fund.rds")
```

## Wrangle and Plots

```{r}
# Get Median Fund
median_fund <- get_median_fund_q1(ASISA)
print(paste("Median fund is:", median_fund))

# Calculate Net Returns for Median Fund
median_fund_data <- ASISA %>%
  filter(Fund == median_fund) %>%
  calc_net_fees_q1(return_column = "Returns", fee_bps = 200)

# Align Data
aligned_data <- align_data_q1(median_fund_data, AI_Fund, BM)

# Plot Rolling Returns
plot_rolling_returns_q1(aligned_data, 
                        date_column = "date", 
                        return_columns = c("Median_Fund_Net", "AI_Fund_Return", "BM_Return"))

# Plot Rolling Density
plot_rolling_density_q1(aligned_data, 
                        date_column = "date", 
                        return_columns = c("Median_Fund_Net", "AI_Fund_Return", "BM_Return"))



```

